# Generated by Django 5.2.8 on 2025-11-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('api', 'API Development'), ('design', 'UI/UX Design'), ('consulting', 'Consulting'), ('devops', 'DevOps & Deployment')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('project_requirements', models.TextField()),
                ('preferred_timeline', models.CharField(blank=True, choices=[('asap', 'As soon as possible'), ('2-4 weeks', '2-4 weeks'), ('1-2 months', '1-2 months'), ('2-3 months', '2-3 months'), ('3+ months', '3+ months'), ('flexible', 'Flexible')], max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('Under $1,000', 'Under $1,000'), ('$1,000 - $2,500', '$1,000 - $2,500'), ('$2,500 - $5,000', '$2,500 - $5,000'), ('$5,000 - $10,000', '$5,000 - $10,000'), ('$10,000+', '$10,000+'), ('not-sure', 'Not sure / Need quote')], max_length=50)),
                ('agree_to_terms', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
